services:
  ufc-scraper:
    container_name: ufc-scraper
    build:
      context: .
      dockerfile: Dockerfiles/scraper.Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DB_URI: ${DB_URI} 
      LOG_DIR: ${LOG_DIR} 
    command: python ./scraper/ufc_fights.py --build 

