ufcdbt:
  outputs:
    local:
      dbname: ufcdb
      host: localhost
      pass: ufc
      port: 5432
      schema: dbt_schema
      threads: 32
      type: postgres
      user: ufc
    cloud:
      dbname: neondb
      host: ep-shy-dream-a7h5ch01-pooler.ap-southeast-2.aws.neon.tech
      pass: npg_T5l8XdCbYWjh
      port: 5432
      schema: dbt_schema
      threads: 32
      type: postgres
      user: neondb_owner

  targets:
    - local
    - cloud 