sources:
  - name: ufcdb
    description: "Source of ufc data"
    database: ufcdb
    schema: public
    tables:
      - name: fighters
        description: "contains information about UFC fighters"
      - name: events 
        description: "contains information about UFC fights"
      - name: fights
        description: "contains information about UFC events"