
version: 2

models:
  - name: events_raw
    description: table of ufc events
    columns:
      - name: id
        description: "Primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: date 
        description: "date of the event"
        data_tests:
          - not_null
      - name: city 
        description: "city where event was held"
      - name: state 
        description: "state where event was held"
      - name: country 
        description: "country where event was held"
      - name: venue
        description: "venue where event was held"
  - name: fighters_raw
    description: table of ufc fighters
    columns:
      - name: id
        description: "Primary key for this table"
        tests:
          - unique
          - not_null
      - name: first_name
        description: "First name of the fighter"
      - name: last_name
        description: "Last name of the fighter"
      - name: nickname
        description: "Nickname of the fighter"
      - name: hometown_city
        description: "Hometown city of the fighter"
      - name: hometown_state
        description: "Hometown state of the fighter"
      - name: hometown_country
        description: "Hometown country of the fighter"
      - name: trains_at_city
        description: "City where the fighter trains"
      - name: trains_at_state
        description: "State where the fighter trains"
      - name: trains_at_country
        description: "Country where the fighter trains"
      - name: wins
        description: "Number of wins"
      - name: losses
        description: "Number of losses"
      - name: draws
        description: "Number of draws"
      - name: age
        description: "Age of the fighter"
      - name: height
        description: "Height of the fighter"
      - name: stance
        description: "Stance of the fighter"
      - name: reach
        description: "Reach of the fighter"
      - name: weight
        description: "Weight of the fighter"
      - name: url
        description: "URL of the fighter's profile"
      - name: last_updated_at
        description: "Timestamp of the last update"

      
