sources:
  - name: database 
    description: "Source of ufc data"
    database: "{{ target.dbname }}" 
    schema: public
    tables:
      - name: raw_events 
        description: "contains raw event data from ufc api"
        columns:
        - name: id
          description: "Primary key for this table"
          data_tests:
            - unique
            - not_null
        - name: date 
          description: "date of the event"
          data_tests:
            - not_null
        - name: city 
          description: "city where event was held"
        - name: state 
          description: "state where event was held"
        - name: country 
          description: "country where event was held"
        - name: venue
          description: "venue where event was held"

      - name: raw_fighters
        description: "contains raw fighter data from ufc api"
        columns:
        - name: id
          description: "Primary key for this table"
          tests:
            - unique
            - not_null
        - name: first_name
          description: "First name of the fighter"
        - name: last_name
          description: "Last name of the fighter"
        - name: nickname
          description: "Nickname of the fighter"
        - name: hometown_city
          description: "Hometown city of the fighter"
        - name: hometown_state
          description: "Hometown state of the fighter"
        - name: hometown_country
          description: "Hometown country of the fighter"
        - name: trains_at_city
          description: "City where the fighter trains"
        - name: trains_at_state
          description: "State where the fighter trains"
        - name: trains_at_country
          description: "Country where the fighter trains"
        - name: trains_at_country_tricode
          description: "Country tricode where the fighter trains"
        - name: wins
          description: "Number of wins"
        - name: losses
          description: "Number of losses"
        - name: draws
          description: "Number of draws"
        - name: age
          description: "Age of the fighter"
        - name: height
          description: "Height of the fighter"
        - name: stance
          description: "Stance of the fighter"
        - name: reach
          description: "Reach of the fighter"
        - name: weight_class_data
          description: "raw json data of fighters weight class"
        - name: url
          description: "URL of the fighter's profile"
        - name: last_updated_at
          description: "Timestamp of the last update"

      - name: raw_fights
        description: "contains raw fight data from ufc api"
        columns:
        - name: id
          description: "unique identifer of the fight" 
          tests:
            - unique
            - not_null
        - name: event_id
          description: "foreign key of the event table"
          tests:
            - not_null
        - name: r_fighter_id
          description: "ID of the red corner fighter"
          tests:
            - not_null
        - name: b_fighter_id
          description: "ID of the blue corner fighter"
          tests:
            - not_null
        - name: r_fighter_status
          description: "Status of the red corner fighter (e.g., win, loss)"
          tests:
            - not_null
        - name: b_fighter_status
          description: "Status of the blue corner fighter (e.g., win, loss)"
          tests:
            - not_null
        - name: round
          description: "Round in which the fight ended"
          tests:
            - not_null
        - name: time
          description: "Time in the round when the fight ended"
          tests:
            - not_null
        - name: method
          description: "Method of victory (e.g., KO, submission)"
          tests:
            - not_null
        - name: bout_weight
          description: "Weight class of the fight"
        - name: r_fight_stats
          description: "All the red corners fight stats in json format"
          tests:
            - not_null
        - name: b_fight_stats
          description: "All the blue corners fight stats in json format"
          tests:
            - not_null
        - name: url
          description: "API url for the fight"
          tests:
            - not_null
        - name: last_updated_at
          description: "Timestamp of the last update"
          tests:
            - not_null
        - name: start_time
          description: "time event was held"
          tests:
            - not_null