version: 2

models:
  - name: stg_fighters
    description: "Staging table for UFC fighters with cleaned and transformed data"
    columns:
      - name: id
        description: "Primary key for the fighter"
        tests:
          - unique
          - not_null
      - name: first_name
        description: "First name of the fighter"
        tests:
          - not_null
      - name: last_name
        description: "Last name of the fighter"
        tests:
          - not_null
      - name: nickname
        description: "Nickname of the fighter"
      - name: hometown_city
        description: "Hometown city of the fighter"
      - name: hometown_state
        description: "Hometown state of the fighter"
      - name: hometown_country
        description: "Hometown country of the fighter"
      - name: trains_at_city
        description: "City where the fighter trains"
      - name: trains_at_state
        description: "State where the fighter trains"
      - name: trains_at_country
        description: "Country where the fighter trains"
      - name: wins
        description: "Number of wins"
        tests:
          - not_null
          - expression: 
              sql: "wins >= 0"
      - name: losses
        description: "Number of losses"
        tests:
          - not_null
          - expression: 
              sql: "losses >= 0"
      - name: draws
        description: "Number of draws"
        tests:
          - not_null
          - expression: 
              sql: "draws >= 0"
      - name: age
        description: "Age of the fighter"
      - name: height
        description: "Height of the fighter in centimeters"
      - name: stance
        description: "Stance of the fighter (e.g., orthodox, southpaw)"
      - name: reach
        description: "Reach of the fighter in centimeters"
      - name: weight
        description: "Weight of the fighter in pounds"
      - name: weight_division
        description: "Weight division of the fighter (e.g., lightweight, heavyweight)"
      - name: url
        description: "URL of the fighter's profile"
      - name: last_updated_at
        description: "Timestamp of the last update"
        tests:
          - not_null

  - name: stg_events 
    columns:
      - name: id
        description: "Primary key for the event"
        tests:
          - unique
          - not_null
      - name: name
        description: "Name of the event"
        tests:
          - not_null
      - name: date
        description: "Date of the event"
        tests:
          - not_null
      - name: city
        description: "City where the event was held"
      - name: state
        description: "State where the event was held"
      - name: country
        description: "Country where the event was held"
        tests:
          - not_null
      - name: venue
        description: "Venue where the event was held"
      - name: last_updated_at
        description: "Timestamp of the last update"
        tests:
          - not_null

  - name: stg_fights
  