version: 2

models:
  - name: stg_events 
    description: "Staging table for UFC events with cleaned and transformed data"
    columns:
      - name: id
        description: "Primary key for the event"
        tests:
          - unique
          - not_null
      - name: name
        description: "Name of the event"
        tests:
          - not_null
      - name: date
        description: "Date of the event"
        tests:
          - not_null
      - name: country
        description: "Country where the event was held"
        tests:
          - not_null
      - name: venue
        description: "Venue where the event was held"
      - name: last_updated_at
        description: "Timestamp of the last update"
        tests:
          - not_null

  - name: stg_fighters
    description: "Staging table for UFC fighters with cleaned and transformed data"
    columns:
      - name: id
        description: "Primary key for the fighter"
        tests:
          - unique
          - not_null
      - name: last_name
        description: "Last name of the fighter"
        tests:
          - not_null
      - name: wins
        description: "Number of wins"
        tests:
          - not_null
      - name: losses
        description: "Number of losses"
        tests:
          - not_null
      - name: draws
        description: "Number of draws"
        tests:
          - not_null


  - name: stg_fights
    description: "Staging table for UFC fights with cleaned and transformed data"
    columns:
      - name: id
        description: "Primary key for the fight"
        tests:
          - unique
          - not_null
      - name: event_id
        description: "Foreign key to the event table"
        tests:
          - not_null
      - name: r_fighter_id
        description: "ID of the red corner fighter"
        tests:
          - not_null
      - name: b_fighter_id
        description: "ID of the blue corner fighter"
        tests:
          - not_null
      - name: r_fighter_status
        description: "Status of the red corner fighter (e.g., win, loss)"
        tests:
          - not_null
      - name: b_fighter_status
        description: "Status of the blue corner fighter (e.g., win, loss)"
        tests:
          - not_null
      - name: ending_round
        description: "Round in which the fight ended"
        tests:
          - not_null
      - name: bout_rounds
        description: "Set rounds of the bout"
        tests:
          - not_null
          - assert_valid_rounds
      - name: time
        description: "Time in the round when the fight ended"
        tests:
          - not_null
      - name: method
        description: "Method of victory (e.g., KO, submission)"
        tests:
          - not_null
      - name: method_type
        description: "numeric conversion of method KO - 1, sub - 2, dec - 3, other - 0"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [0, 1, 2, 3]
      - name: bout_weight
        description: "Weight class of the fight"
        tests:
          - not_null
      - name: bout_weight_id
        description: "Weight class ID of the fight"
        tests:
          - not_null
      - name: fight_date
        description: "date of the fight"
        tests:
          - not_null
          - assert_after_2000
      - name: url
        description: "API url for the fight"
        tests:
          - not_null
      - name: last_updated_at
        description: "Timestamp of the last update"
        tests:
          - not_null
      - name: clinch_time 
        description: "total clinch time (in 00:00 format)"
      - name: ground_time 
        description: "total ground time (in 00:00 format)"
      - name: standing_time 
        description: "total standing time (in 00:00 format)"
      - name: r_knockdowns 
        description: "red corner total knockdowns"
        tests:
          - not_null
      - name: b_knockdowns 
        description: "blue corner total knockdowns"
        tests:
          - not_null
      - name: r_takedowns_landed
        description: "red corner takedowns"
        tests:
          - not_null
      - name: b_takedowns_landed
        description: "blue corner takedowns"
        tests:
          - not_null
      - name: r_takedowns_attempted
        description: "red corner takedown attempts"
        tests:
          - not_null
      - name: b_takedowns_attempted
        description: "blue corner takedown attempts"
        tests:
          - not_null
      - name: r_sig_strikes_landed
        description: "red corner significant strikes landed"
        tests:
          - not_null
      - name: b_sig_strikes_landed
        description: "blue corner significant strikes landed"
        tests:
          - not_null
      - name: r_sig_strikes_attempted
        description: "red corner significant strikes attempted"
        tests:
          - not_null
      - name: b_sig_strikes_attempted
        description: "blue corner significant strikes attempted"
        tests:
          - not_null
      - name: r_sig_strikes_accuracy
        description: "red corner significant strikes accuracy"
        tests:
          - not_null
      - name: b_sig_strikes_accuracy
        description: "blue corner significant strikes accuracy"
        tests:
          - not_null
      - name: r_total_strikes_landed
        description: "red corner strikes landed"
        tests:
          - not_null
      - name: b_total_strikes_landed
        description: "blue corner strikes landed"
        tests:
          - not_null
      - name: r_total_strikes_attempted
        description: "red corner strikes attempted"
        tests:
          - not_null
      - name: b_total_strikes_attempted
        description: "blue corner strikes attempted"
        tests:
          - not_null
      - name: r_submissions_attempted
        description: "red corner submissions attempted"
        tests:
          - not_null
      - name: b_submissions_attempted
        description: "blue corner submissions attempted"
        tests:
          - not_null
      - name: r_control_time
        description: "red corner total control time"
      - name: b_control_time
        description: "blue corner total control time"
      - name: r_clinch_control_time
        description: "red corner clinch control time"
      - name: b_clinch_control_time
        description: "blue corner clinch control time"
      - name: r_ground_control_time
        description: "red corner ground control time"
      - name: b_ground_control_time
        description: "blue corner ground control time"
