version: 2

models:
  - name: stg_fighters
    description: "Staging table for UFC fighters with cleaned and transformed data"
    columns:
      - name: id
        description: "Primary key for the fighter"
        tests:
          - unique
          - not_null
      - name: first_name
        description: "First name of the fighter"
        tests:
          - not_null
      - name: last_name
        description: "Last name of the fighter"
        tests:
          - not_null
      - name: nickname
        description: "Nickname of the fighter"
      - name: hometown_city
        description: "Hometown city of the fighter"
      - name: hometown_state
        description: "Hometown state of the fighter"
      - name: hometown_country
        description: "Hometown country of the fighter"
      - name: trains_at_city
        description: "City where the fighter trains"
      - name: trains_at_state
        description: "State where the fighter trains"
      - name: trains_at_country
        description: "Country where the fighter trains"
      - name: wins
        description: "Number of wins"
        tests:
          - not_null
      - name: losses
        description: "Number of losses"
        tests:
          - not_null
      - name: draws
        description: "Number of draws"
        tests:
          - not_null
      - name: age
        description: "Age of the fighter"
      - name: height
        description: "Height of the fighter in centimeters"
      - name: stance
        description: "Stance of the fighter (e.g., orthodox, southpaw)"
      - name: reach
        description: "Reach of the fighter in centimeters"
      - name: weight
        description: "Weight of the fighter in pounds"
      - name: weight_division
        description: "Weight division of the fighter (e.g., lightweight, heavyweight)"
      - name: url
        description: "URL of the fighter's profile"
      - name: last_updated_at
        description: "Timestamp of the last update"
        tests:
          - not_null

  - name: stg_events 
    description: "Staging table for UFC events with cleaned and transformed data"
    columns:
      - name: id
        description: "Primary key for the event"
        tests:
          - unique
          - not_null
      - name: name
        description: "Name of the event"
        tests:
          - not_null
      - name: date
        description: "Date of the event"
        tests:
          - not_null
      - name: city
        description: "City where the event was held"
      - name: state
        description: "State where the event was held"
      - name: country
        description: "Country where the event was held"
        tests:
          - not_null
      - name: venue
        description: "Venue where the event was held"
      - name: last_updated_at
        description: "Timestamp of the last update"
        tests:
          - not_null

  - name: stg_fights
    description: "Staging table for UFC fights with cleaned and transformed data"
    columns:
      - name: id
        description: "Primary key for the fight"
        tests:
          - unique
          - not_null
      - name: event_id
        description: "Foreign key to the event table"
        tests:
          - not_null
      - name: r_fighter_id
        description: "ID of the red corner fighter"
        tests:
          - not_null
      - name: b_fighter_id
        description: "ID of the blue corner fighter"
        tests:
          - not_null
      - name: r_fighter_status
        description: "Status of the red corner fighter (e.g., win, loss)"
        tests:
          - not_null
      - name: b_fighter_status
        description: "Status of the blue corner fighter (e.g., win, loss)"
        tests:
          - not_null
      - name: round
        description: "Round in which the fight ended"
        tests:
          - not_null
      - name: time
        description: "Time in the round when the fight ended"
        tests:
          - not_null
      - name: method
        description: "Method of victory (e.g., KO, submission)"
        tests:
          - not_null
      - name: method_type
        description: "numeric conversion of method KO - 1, sub - 2, dec - 3, other - 0"
        tests:
          - not_null
      - name: bout_weight
        description: "Weight class of the fight"
      - name: url
        description: "API url for the fight"
        tests:
          - not_null
      - name: last_updated_at
        description: "Timestamp of the last update"
        tests:
          - not_null
      - name: clinch_time 
        description: "total clinch time (in 00:00 format)"
      - name: ground_time 
        description: "total ground time (in 00:00 format)"
      - name: standing_time 
        description: "total standing time (in 00:00 format)"
      - name: r_knockdowns 
        description: "red corner total knockdowns"
        tests:
          - not_null
      - name: b_knockdowns 
        description: "blue corner total knockdowns"
        tests:
          - not_null
      - name: r_takedowns_landed
        description: "red corner takedowns"
        tests:
          - not_null
      - name: b_takedowns_landed
        description: "blue corner takedowns"
        tests:
          - not_null
      - name: r_takedowns_attempted
        description: "red corner takedown attempts"
        tests:
          - not_null
      - name: b_takedowns_attempted
        description: "blue corner takedown attempts"
        tests:
          - not_null
      - name: r_sig_strikes_landed
        description: "red corner significant strikes landed"
        tests:
          - not_null
      - name: b_sig_strikes_landed
        description: "blue corner significant strikes landed"
        tests:
          - not_null
      - name: r_sig_strikes_attempted
        description: "red corner significant strikes attempted"
        tests:
          - not_null
      - name: b_sig_strikes_attempted
        description: "blue corner significant strikes attempted"
        tests:
          - not_null
      - name: r_sig_strikes_accuracy
        description: "red corner significant strikes accuracy"
        tests:
          - not_null
      - name: b_sig_strikes_accuracy
        description: "blue corner significant strikes accuracy"
        tests:
          - not_null
      - name: r_total_strikes_landed
        description: "red corner strikes landed"
        tests:
          - not_null
      - name: b_total_strikes_landed
        description: "blue corner strikes landed"
        tests:
          - not_null
      - name: r_total_strikes_attempted
        description: "red corner strikes attempted"
        tests:
          - not_null
      - name: b_total_strikes_attempted
        description: "blue corner strikes attempted"
        tests:
          - not_null
      - name: r_submissions_attempted
        description: "red corner submissions attempted"
        tests:
          - not_null
      - name: b_submissions_attempted
        description: "blue corner submissions attempted"
        tests:
          - not_null
      - name: r_control_time
        description: "red corner total control time"
      - name: b_control_time
        description: "blue corner total control time"
      - name: r_clinch_control_time
        description: "red corner clinch control time"
      - name: b_clinch_control_time
        description: "blue corner clinch control time"
      - name: r_ground_control_time
        description: "red corner ground control time"
      - name: b_ground_control_time
        description: "blue corner ground control time"
