SELECT
  id,
  first_name,
  last_name,
  (first_name || ' '  || last_name) AS full_name,
  nickname AS "nick_name",
  age,
  hometown_city,
  hometown_state,
  hometown_country,
  hometown_country_tricode,
  trains_at_city,
  trains_at_state,
  trains_at_country,
  trains_at_country_tricode,
  wins,
  losses,
  draws,
  {{ inches_to_cm('height') }},
  stance,
  {{ inches_to_cm('reach') }},
  weight_class_data ->> 'WeightClassId' AS "weight_class_id",
  weight_class_data ->> 'WeightClassOrder' AS "weight_class_order",
  weight_class_data ->> 'Description' AS "weight_class_description",
  url,
  last_updated_at
FROM
  {{ source('database', 'raw_fighters')}}