models:
  - name: dim_events
    columns:
      - name: id 
        description: "primary key"
        tests:
          - not_null
          - unique
      - name: name
        description: "name of the event"
        tests:
          - not_null
      - name: date
        description: "date of the event"
        tests:
          - not_null
      - name: city 
        description: "city where the event was held"
        tests:
          - not_null
      - name: state
        description: "state where the event was held"
      - name: country
        description: "country where the event was held"
        tests:
          - not_null
      - name: venue
        description: "name of the venue where the event was held in"
        tests:
          - not_null
  - name: dim_fighters
    columns:
      - name: fighter_id
        description: "primary key"
        tests:
          - not_null
          - unique
      - name: first_name
        description: "first name of the fighter"
      - name: last_name
        description: "last name of the fighter"
      - name: nick_name
        description: "nick name of the fighter"
      - name: weight_class
        description: "weight class of the fighter"
  - name: fact_fights
    columns:
      - name: fight_date
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "fight_date < now()"
      - name: b_fighter_status
        tests:
          - not_null
      - name: r_fighter_status
        tests:
          - not null
            
    